import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from '../components/ReduxProvider';
import ClientWrapper from '../components/ClientWrapper';
import SessionProviderWrapper from '../components/SessionProviderWrapper';
import { ThemeProvider } from "@/components/ThemeProvider";
import AppDataProvider from "@/context";
const inter = Inter({ subsets: ['latin'] });
import AppInitializer from '@/store/slices/AppInitializer';
import socket from "@/services/socket"
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { Toaster } from "@/components/ui/toaster"
import Socket from '@/services/socket';
import MessageListener from '@/services/MessageListener';
// import Socket from '@/services/socket';
// import MessageListener from '@/services/MessageListener';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ fontFamily: "'SfUi', sans-serif" }}>
        <SessionProviderWrapper>
   
          <ReduxProvider>

          <AppInitializer />
          <Socket/>
      <MessageListener/>
          <AppDataProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
              {children}
              <Toaster />
              </ThemeProvider>
              </AppDataProvider>
          </ReduxProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
